Add CSS grid to style three sections.
Addis0943/The-Next-Web pull request #5
Opened 2021-02-25 15:09 UTC by Addis0943

We use CSS grid for three screen sizes to adjust the layout for mobile tablet and laptop. 
we add three new sections to the project.

2021-02-25 17:28 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job on this project :+1: The live link works perfectly  :muscle: The README is looking great :slightly_smiling_face: Most of the requirements have been met :slightly_smiling_face: Let us kindly address the comments below:

- Let us improve the use of HTML semantics, we should use the `<section>` tag for each section, each child of the section should be `<article>` tag
- Kindly avoid repeating code, some of our CSS property values have been repeated, for example; `display: flex` appears 8+ and we should try and clean the code, also check for the other property values
- The PR could be improved to reflect what we specifically did, like name the sections created and the type of positioning used, like grid or flex in the PR would be a great addition
- `Mobile view of latest deals` section is not correctly aligned as in the original. Kindly check and fix it. Kindly check the screenshot below
`Original`
![sc1](https://user-images.githubusercontent.com/46388113/109191328-f6d23f00-778d-11eb-8257-89fc5759b588.png)
`Clone`
![sc](https://user-images.githubusercontent.com/46388113/109191352-fe91e380-778d-11eb-87af-587e97643079.png)
- `Tablet mode of the latest deals` section is not correctly positioned as in the original. We should have 3 columns but we currently have 4 columns. Let us fix it
`Original`
![gn](https://user-images.githubusercontent.com/46388113/109191904-8a0b7480-778e-11eb-8068-f570b386c270.png)
`Clone`
![gn1](https://user-images.githubusercontent.com/46388113/109191939-955ea000-778e-11eb-97ce-8276d9b3ead5.png)

Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-25 17:28 UTC, addod19 commented on index.html
> +    <div class="latest-news">
Kindly replace `<div class="latest-news">` to `<section class="latest-news">` so we improve the use of HTML semantics. Kindly do this for the others

2021-02-25 17:28 UTC, addod19 commented on index.html
> +<div class="car">
Kindly replace `<div class="car">` to `<article class="car">` so we improve the use of HTML semantics. Kindly do this for the others

2021-02-25 17:28 UTC, addod19 commented on index.html
> +<img src="https://lh3.googleusercontent.com/H8wc4zpiBOojdb00UBQL0M8llf9R4-F0zLa5uiPaAup9XbGsEWLaz1V3EA3GTioKA6Vl=s151"
Kindly wrap the `<img>` tag with `<a>` tag

2021-02-25 17:28 UTC, addod19 commented on index.html
> +<a href="#" class="hydrogen">Want to drive a hydrogen EV in the US? Move to California</a>
Kindly wrap the title text with the `<h*>` tags before wrapping the `<h*>` tag with the `<a>` tag. Both the image and the title must be a link

2021-02-25 17:28 UTC, addod19 commented on index.html
> +<div class="Categories">
Kindly replace `<div class="Categories">` to `<section class="Categories">`, so we improve the use of HTML semantics. Kindly do this for the others as well

2021-02-25 17:28 UTC, addod19 commented on index.html
> +<div class="categories-white">
Kindly replace `<div class="categories-white">` with `<article>` tag to improve the use of HTML semantics. Do this for the others

2021-02-25 17:28 UTC, addod19 commented on index.html
> +<div class="latest-deals">
Kindly replace `<div class="latest-deals">` with `<section>` tag so we improve the use of HTML semantics. Do this for the others as well

2021-02-25 17:28 UTC, addod19 commented on index.html
> +        <div class="latest-deal-item">
Kindly replace `<div class="latest-deal-item>` with `<article>` tag so we improve the use of HTML semantics. Do this for the others :smile:

2021-02-26 09:16 UTC, Addis0943 commented
Hello @addod19 :wave: 
Thank you for your clear feedback.
We have used the semantic HTML tag section to group the articles and we have worked on the proper mobile view for the latest deal section. We have used CSS classes to group similar repeated code and have greatly reduced the lines of code.
![latsest-deals](https://user-images.githubusercontent.com/50677754/109280677-66970700-782c-11eb-94c2-ca593eff17e8.png)

2021-02-26 17:59 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, congratulations on fixing the comments from the previous review :muscle: However, in fixing one of the comments we introduced a new approach which is not the recommended one. We are to implement a mobile-first approach which means we have 2 media queries for (768px tablets and (1024px) desktop.

Let us kindly fix this and submit another code review :computer: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-26 17:59 UTC, addod19 commented on style.css
> +@media only screen and (min-width: 481px) {
Hi guys, we are supposed to implement a mobile-first approach which is to have only 2 media queries which are for a tablet (768px) and desktop(1024px). There should be no media query for mobile device :computer:

2021-02-26 18:39 UTC, Addis0943 commented
Hello @addod19
Thank you for your feedback!
we implemented a mobile-first approach.

2021-02-27 08:43 UTC, teekaytech approved these changes
## Status: Approved :green_circle: 

### Congratulations team :tada: 

**Thank you for implementing the changes highlighted by the previous reviewer :handshake:** 

**This project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:**

**Comment(s)**
- In your subsequent PRs, your PR summary should be a brief description of what you did in the milestone. Therefore, in my opinion, you do not have to add your project screenshots: adding screenshots is ideal for the Readme.

**Again, congratulations,** you can now merge to the master branch.
Do not forget to fill the project completion form.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-02-27 11:36 UTC, merged